import os
import sys
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QPalette, QBrush, QColor


def paletteConfig(self):

    self.palette = QPalette()

    #Palette for Active state
    
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.Button, brush)
    brush = QBrush(QColor(85, 1, 188))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.Text, brush)
    brush = QBrush(QColor(57, 1, 125))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.Base, brush)
    brush = QBrush(QColor(57, 1, 125))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.Window, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush)
    brush = QBrush(QColor(57, 1, 125))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.NoRole, brush)
    brush = QBrush(QColor(255, 255, 220))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
    brush = QBrush(QColor(57, 1, 125, 128))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)

    ###################################################################################################
    #Palette for Inactive state

    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.Button, brush)
    brush = QBrush(QColor(85, 1, 188))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
    brush = QBrush(QColor(57, 1, 125))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
    brush = QBrush(QColor(57, 1, 125))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush)
    brush = QBrush(QColor(57, 1, 125))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.NoRole, brush)
    brush = QBrush(QColor(255, 255, 220))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush)
    brush = QBrush(QColor(0, 0, 0))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
    brush = QBrush(QColor(57, 1, 125, 128))
    brush.setStyle(Qt.SolidPattern)
    self.palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
    brush = QBrush(QColor(255, 255, 255))
    brush.setStyle(Qt.SolidPattern)